In [1]:
import numpy as np

In [2]:
ROW_COUNT = 3

In [3]:
COLUMN_COUNT = 3

In [4]:
# Functions

In [5]:
def is_valid_location(board, selection):
    if selection >= 7:
        row = 0
    elif selection >= 4 and selection <= 6:
        row = 1
    else:
        row = 2
    if selection == 7 or selection == 4 or selection == 1:
        col = 0
    elif selection == 8 or selection == 5 or selection == 2:
        col = 1
    else: 
        col = 2
    return board[row][col] == 0

In [6]:
def create_board():
    board = np.zeros((ROW_COUNT , COLUMN_COUNT))
    return board

In [7]:
def place_piece(board, selection, piece):
    if selection >= 7:
        row = 0
    elif selection >= 4 and selection <= 6:
        row = 1
    else:
        row = 2
    if selection == 7 or selection == 4 or selection == 1:
        col = 0
    elif selection == 8 or selection == 5 or selection == 2:
        col = 1
    else: 
        col = 2
    
    board[row][col] = piece

In [8]:
def is_winner(board, selection, piece):
    if selection >= 7:
        row = 0
    elif selection >= 4 and selection <= 6:
        row = 1
    else:
        row = 2
    if selection == 7 or selection == 4 or selection == 1:
        col = 0
    elif selection == 8 or selection == 5 or selection == 2:
        col = 1
    else: 
        col = 2
    
    
    for r in range(len(board)):
        for c in range(len(board)):
            # Check vertical
            if board[0][c] == piece:
                if board[1][c] == piece:
                    if board[2][c] == piece:
                        return True
            # Check Horizontal
            if board[r][0] == piece:
                if board[r][1] == piece:
                    if board[r][2] == piece:
                        return True
            # Check Diagonal
            if board[0][2] == piece:
                if board[1][1] == piece:
                    if board[2][0] == piece:
                        return True
            # Check Diagnal 2
            if board[0][0] == piece:
                if board[1][1] == piece:
                    if board[2][2] == piece:
                        return True
           
                

In [9]:
def is_draw(board):
     # Check Draw
    if not 0 in board and is_winner(board, selection, piece):
        return True

In [10]:
# Needed Variables
# Game over to end for loop
# turn to determine which player1 or player2 
# Function place piece 
# Function that checks valid location 
# Function that checks for winning move

In [11]:
# Variables
game_over = False

In [12]:
board = create_board()

In [13]:
turn = 0

In [14]:
# Create Board

print(board)


# Main Game loop


while not game_over:
    # player turn logic
    if turn == 0:
        # Get player1 input
        selection = int(input("Player 1 using Numpad pick a number (1-9): "))
        if is_valid_location(board, selection):
            place_piece(board, selection, 1)
            if is_winner(board, selection, 1):
                print('Player 1 You Win!')
                print(board)
                replay_game = str(input('Do you want to play again? YES or NO '))
                if replay_game.upper() == 'YES':
                    turn = 1
                    board = create_board()
                    game_over = False
                elif replay_game.upper() == 'NO':
                    print('GAME OVER')
                    game_over = True
                else: 
                    print('Try Again!')
            elif 0 not in board:
                print('Game is a Draw')
                print(board)
                replay_game = str(input('Do you want to play again? YES or NO '))
                if replay_game.upper() == 'YES':
                    turn = 0
                    board = create_board()
                    game_over = False
                elif replay_game.upper() == 'NO':
                    print('GAME OVER')
                    game_over = True
                else: 
                    print('Try Again!')
        else:
            print('Try Again! ')
            turn = 1
    
    
    else:
        # Get player2 input
        selection = int(input("Player 2 using Numpad pick a number (1-9): "))
        if is_valid_location(board, selection):
            place_piece(board, selection, 2)
            if is_winner(board, selection, 2):
                print('Player 2 You Win!')
                print(board)
                replay_game = str(input('Do you want to play again? YES or NO '))
                if replay_game.upper() == 'YES':
                    turn = 0
                    board = create_board()
                    game_over = False
                elif replay_game.upper() == 'NO':
                    print('GAME OVER')
                    game_over = True
                else: 
                    print('Try Again!')
            elif 0 not in board:
                print('Game is a Draw')
                print(board)
                replay_game = str(input('Do you want to play again? YES or NO '))
                if replay_game.upper() == 'YES':
                    turn = 0
                    board = create_board()
                    game_over = False
                elif replay_game.upper() == 'NO':
                    print('GAME OVER')
                    game_over = True
                else: 
                    print('Try Again!')
        else:
            print('Try Again! ')
            turn = 0
            
    turn += 1
    turn = turn % 2
    print(board)
 

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Player 1 using Numpad pick a number (1-9): 1
[[0. 0. 0.]
 [0. 0. 0.]
 [1. 0. 0.]]
Player 2 using Numpad pick a number (1-9): 9
[[0. 0. 2.]
 [0. 0. 0.]
 [1. 0. 0.]]
Player 1 using Numpad pick a number (1-9): 6
[[0. 0. 2.]
 [0. 0. 1.]
 [1. 0. 0.]]
Player 2 using Numpad pick a number (1-9): 3
[[0. 0. 2.]
 [0. 0. 1.]
 [1. 0. 2.]]
Player 1 using Numpad pick a number (1-9): 5
[[0. 0. 2.]
 [0. 1. 1.]
 [1. 0. 2.]]
Player 2 using Numpad pick a number (1-9): 8
[[0. 2. 2.]
 [0. 1. 1.]
 [1. 0. 2.]]
Player 1 using Numpad pick a number (1-9): 4
Player 1 You Win!
[[0. 2. 2.]
 [1. 1. 1.]
 [1. 0. 2.]]
Do you want to play again? YES or NO no
GAME OVER
[[0. 2. 2.]
 [1. 1. 1.]
 [1. 0. 2.]]
